os: linux
arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
language: cpp
compiler:
  - gcc
  - clang

sudo: required

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ./endianness-test
